config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :portfolio, only: [:show], id: 'default'
  resources :aboutme, only: [:show], id: 'default'
  resources :contact, only: [:show], id: 'default'


  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/aboutme.rb
class Aboutme < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord

  has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/aboutme_controller.rb
class AboutmeController < ApplicationController
  def show
    @aboutme = Aboutme.find_by(id: params[:id] || 'default')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def show
    @contact = Contact.find_by(id: params[:id] || 'default')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def show
    @portfolio = Portfolio.find_by(id: params[:id] || 'default')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/aboutme/show.html.erb
<h1>It's working 🎉</h1>
// Photo //
  <div class="card-container">
      <div class="card projeto">
        <img src="assets/images/leaf.jpg" class="d-block" alt="...">
        <%# <div class="card-body">
          <h2 class="card-title">Flowers</h2>
          <p class="card-text">An easier, faster way to throw a meal together</p>
          <p>Colaborated Project</p>
        </div> %>
      </div>
    </a>
  </div>
// About //
<div class="container text">
  <h3>A little bit about me </h3>
  <h4>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</h4>
</div>

app/views/contact/show.html.erb
<h1>It's working 🎉</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SamDavydesign</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&family=Indie+Flower&family=Licorice&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body><%= render "shared/navbar" %>
        <%= render "shared/flashes" %>

    <%= yield %>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
    <a href="<%= portfolio_path %>" style="text-decoration: none; ">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="10000">
        <img src="assets/leaf.jpg" class="d-block w-100" alt="..."style="border-radius: 20px;">
        <div class="carousel-caption d-none d-md-block">
          <%# <h5>First slide label</h5>
          <p>Some representative placeholder content for the first slide.</p> %>
        </div>
      </div>
      <div class="carousel-item" data-bs-interval="2000">
        <img src="assets/sun.jpg" class="d-block w-100" alt="..."style="border-radius: 20px;">
        <div class="carousel-caption d-none d-md-block">
          <%# <h5>Second slide label</h5>
          <p>Some representative placeholder content for the second slide.</p> %>
        </div>
      </div>
      <div class="carousel-item">
        <img src="assets/cravo.jpg" class="d-block w-100" alt="..."style="border-radius: 20px;">
        <div class="carousel-caption d-none d-md-block">
          <%# <h5>Third slide label</h5>
          <p>Some representative placeholder content for the third slide.</p> %>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <div class="d-flex justify-content-between cards">
    <div class="card-container">
      <a href="<%= aboutme_path %>" style="text-decoration: none; ">
        <div class="my-4 card flower">
          <img src="assets/flower2.jpg" alt="...">
          <div class="card-body">
            <h2 class="card-title">About Me</h2>
          </div>
        </div>
      </a>
    </div>
    <div class=card-container">
      <a href="<%= contact_path %>" style="text-decoration: none; ">
        <div class="my-4 card bouquet">
          <img src="assets/bouquet.jpg" alt="...">
          <div class="card-body">
            <h2 class="card-title">Contact</h2>
          </div>
        </div>
      </a>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="logo">
      <div class="title">
        <h1 style="font-family: Licorice; font-size: 73px;">SamDavy</h1>
      </div>
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Portfolio", portfolio_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", aboutme_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</div>